- hosts: workstation
  roles:
    - { role: git, tags: "git" }
    - { role: dev-tools, tags: "dev-tools" }
    - { role: fonts, tags: "fonts" }
    - { role: macvim, tags: "macvim" }
    - { role: fish, tags: "fish" }
    - { role: python-dev, tags: "python-dev" }
